platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

# use for swift support
use_frameworks!

# per pod basis warning inhibits? =>  use :inhibit_warnings => true
inhibit_all_warnings!

# Add your pods below and specify an explicit version number. Use the following as an example

target "CrossFit Games" do
    # https://github.com/Alamofire/Alamofire/releases
    pod 'Alamofire', '4.5.1'

    # https://github.com/Alamofire/AlamofireImage/releases
    pod 'AlamofireImage', '3.3.0'

    # https://docs.fabric.io/apple/changelog.html#crashlytics
    pod 'Crashlytics', '3.9.3'

    # http://cocoadocs.org/docsets/Fabric/
    pod 'Fabric', '1.7.2'

    # https://firebase.google.com/?authuser=0
    pod 'Firebase/Core', '4.7.0'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'

    # https://github.com/prolificinteractive/Marker/releases
    pod 'Marker', :git => 'https://github.com/prolificinteractive/Marker.git', :branch => 'swift-4'

    # https://github.com/Daltron/NotificationBanner
    pod 'NotificationBannerSwift', '1.5.1'

    # https://developers.google.com/youtube/v3/guides/ios_youtube_helper
    pod 'youtube-ios-player-helper', '0.1.6'

    # https://github.com/kishikawakatsumi/KeychainAccess
    pod 'KeychainAccess', '3.1.0'

    # https://github.com/shima11/FlexiblePageControl
    pod 'FlexiblePageControl', '1.0.5'

    # https://github.com/airbnb/lottie-ios
    pod 'lottie-ios', '2.1.3'

    # https://github.com/prolificinteractive/simcoe
    pod 'Simcoe', '1.2.0'

    # https://github.com/facebook/facebook-sdk-swift
    pod 'FacebookCore', '0.3.0'

    ######################
    ### DO NOT RELEASE ###
    ######################

    # Must not be included in AppStore builds
    # http://hockeyapp.net/releases/
    pod 'HockeySDK', '5.0.0', :configurations => ['Beta', 'Alpha', 'Debug']

    # https://github.com/Instabug/Instabug-iOS/releases
    pod 'Instabug', '7.8.1', :configurations => ['Beta', 'Alpha', 'Debug']

    # https://github.com/prolificinteractive/Yoshi/releases
    pod 'Yoshi', '3.0.0-beta.1', :configurations => ['Beta', 'Alpha', 'Debug']

    # https://github.com/kasketis/netfox
    pod 'netfox', '1.10.5', :configurations => ['Beta', 'Alpha', 'Debug']

    # https://github.com/facebook/Shimmer
    pod 'Shimmer', '1.0.2'

end

target "CrossFit GamesTests" do

    # https://github.com/Alamofire/Alamofire/releases
    pod 'Alamofire', '4.5.1'

    # https://firebase.google.com/?authuser=0
    pod 'Firebase/Core', '4.7.0'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end

plugin 'cocoapods-keys', {
    :project => "CrossFit Games",
    :keys => [
    "ClientID",
    "ClientSecret",
    "HockeyAppID",
    "Instabug"
    ]
}
